### ISSUE TITLE
AMO download link missing

### ISSUE THREAD

**Issue by TheQuickFox** [phreaknerd/passhash-ng#16] opened 2017-11-23 23:21 UTC
I'm looking for an alternative for Password Hasher for Firefox which no longer works with Firefox 57+ (Quantum)

I was pointed to this version but the AMO link seems to be broken now:
https://addons.mozilla.org/en-US/firefox/addon/password-hasher-ng/

Page not found

Sorry, but we can't find anything at the address you entered.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

**Comment by phreaknerd** [comment] 2017-11-24 08:28
Guessing that this was caused by the experimental status of the extension. I've changed that and uploaded a new version. Please try again and close this issue if it's working.

 Thank you!

**Comment by TheQuickFox** [comment] 2017-11-24 11:29
Thanks. I downloaded it. I really **realy** appreciate you taking this add-on to FF Quantum 57.

**Closed as completed** 2017-11-24 13:30 UTC
