### ISSUE TITLE
Importing from the old add-on

### ISSUE THREAD

**Issue by orenbenkiki** [phreaknerd/passhash-ng#24] opened 2017-11-27 10:23 UTC
It would be great if it were possible to import the per-site setup (bump number, size, special characters, etc.). I have been using the old add-on for years and quite a lot has been collected there...

**Comment by phreaknerd** [comment] 2017-12-01 11:58
Duplicate of https://github.com/phreaknerd/passhash-ng/issues/8

**Closed as completed by phreaknerd** 2017-12-01 11:58 UTC
Labels: duplicate
