### ISSUE TITLE
Import/Export per-site settings

### ISSUE THREAD

**Issue by orenbenkiki** [phreaknerd/passhash-ng#25] opened 2017-11-27 10:24 UTC
It would be very useful to be able to export the per-site setup (bump number, password size, special characters etc.) - say as a JSON file - and, of course, also be able to import it back in.

This would allow synchronizing between different computers, creating backups, dealing with version upgrades, etc.

**Comment by phreaknerd** [comment] 2017-12-01 11:58
Duplicate of https://github.com/phreaknerd/passhash-ng/issues/14

**Closed as completed by phreaknerd** 2017-12-01 11:58 UTC
Labels: duplicate
