### ISSUE TITLE
wrong sitetack

### ISSUE THREAD

**Issue by vobexo** [phreaknerd/passhash-ng#34] opened 2018-07-31 16:42 UTC
Hi,
at https://www.shoop.de/ passhash-ng get a wrong sitetack!

instead of Shoop it shows cashbackdeals ?!
![shoop](https://user-images.githubusercontent.com/15708369/43473477-898951a4-94f0-11e8-83f2-1ab2394a67c7.jpg)

**Comment by vobexo** [comment] 2018-08-07 18:40
not sure if it was my PC, on other Pc the error does not occur

**Comment by phreaknerd** [comment] 2018-08-09 07:36
Ok, thanks. I'll close this ticket as a can't reproduce this behaviour. 
Feel free to comment on this ticket again if the error occurs again.

**Closed by phreaknerd** 2018-08-09 07:36 UTC
