### ISSUE TITLE
Size option is not shown intuitive

### ISSUE THREAD

**Issue by reklawykSekuL** [phreaknerd/passhash-ng#15] opened 2017-11-23 20:01 UTC
can be fixed if .form-group.radio.width is set to:

.form-group.radio {
  width: 120px;
}

**Comment by phreaknerd** [comment] 2017-11-24 08:10
What do you mean with intuitive? 
This is by design as I wanted to have it in two columns in the hasher-popup.

**Comment by reklawykSekuL** [comment] 2017-11-25 11:34
On Ubuntu 16.04LTS  with FF 57  and Password Hasher NG 1.0beta-5 it looks like this:
![bildschirmfoto vom 2017-11-25 12-21-26](https://user-images.githubusercontent.com/25550681/33230084-efa28564-d1dc-11e7-909e-cd2e0310babf.jpg)
![bildschirmfoto vom 2017-11-25 12-22-32](https://user-images.githubusercontent.com/25550681/33230085-efcedf6a-d1dc-11e7-939e-f1d9104df9e4.jpg)
when i modified the width to 120 with the WebDeveloper Extension on the running Addon it looks fine.
maybe we need different values on different OS's ?

**Comment by phreaknerd** [comment] 2017-11-25 11:48
Well, you're right. Thats not intuitive... :-D 
I'll check that.

**Comment by vobexo** [comment] 2017-11-25 12:36
Hi,
can you change that the PW Hash-NG Window are closed by klick on the Ok Button? 
Like the old original PW Hasher addon?
I dont´t want to make an extra klick on the X Button from the Window.
System: Windows10, Firefox  57.0, Ver.1.Beta-9

Thx

**Comment by phreaknerd** [comment] 2017-12-01 12:12
I've now checked that on Ubuntu 16 (with gnome-shell), Windows and OSX. Seems ok for me now. Please give a message if the problem is still present.

**Closed as completed by phreaknerd** 2017-12-01 12:12 UTC

**Comment by orenbenkiki** [comment] 2017-12-03 17:38
I don't think this is quite fixed...

This is how it looks in Windows 10, latest version as of positing this. Note the large blank space at the bottom.

![image](https://user-images.githubusercontent.com/68190/33527861-61238218-d860-11e7-99fe-9daa858abc01.png)

And this is how it looks when clicking the options button, note the scroll bar due to the window being clipped:

![image](https://user-images.githubusercontent.com/68190/33527869-a2603802-d860-11e7-9167-bc4e9159d472.png)

Resizing to make all options visible, note the scroll bar is still visible since we didn't _quite_ resize it to be  large enough:

![image](https://user-images.githubusercontent.com/68190/33527887-e37b8ecc-d860-11e7-8c43-d0f7cb72c877.png)

Resize just a bit more, until the scroll bar disappeared; when that happens, the layout switches to two columns, leaving a very large blank space at the bottom:

![image](https://user-images.githubusercontent.com/68190/33527902-1834608a-d861-11e7-977a-89d3ea71c74a.png)

BTW, I'd be happier if the options were always visible, with no button or resize necessary, using "very dumb" layout (possibly even using tables based layout :-) for maximal robustness.

**Comment by reklawykSekuL** [comment] 2017-12-03 21:26
Hi Carsten

i've still the problems with the "Size Option Field"  tested with Version 1.0beta-11

in the options.css  and in  popup.css   the .form-group.radio li  is   50px   width
                                                                                                       + 5px   margin-right
                                                                                                       ==========
                                                                                                         55px

and      2x     .form-group.radio li     in   .form-group.radio  =          110px
and then then the layout of the size option radio's  is ok

in the popup window when selected from the addressbar icon  the layout of the options is ok - you can toggle with the options button and layout is stable
![bildschirmfoto vom 2017-12-03 22-35-34](https://user-images.githubusercontent.com/25550681/33530247-4098836e-d87d-11e7-82d0-a7d336387237.jpg)

in the popup window when selected from the # icon  the layout of the options is not ok and not stable when you toggle the options

![bildschirmfoto vom 2017-12-03 22-36-40](https://user-images.githubusercontent.com/25550681/33530283-a3290030-d87d-11e7-81f5-8d2461955c0e.jpg)

sometimes the size options radio list field is placed right to the requirements options (as expected)
